[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/reports/taf"
  to = "https://aviationweather.gov/api/data/taf"
  status = 200
  force = true

  [redirects.headers]
    "User-Agent" = "flightplan/0.1"

[[redirects]]
  from = "/api/reports/metar"
  to = "https://aviationweather.gov/api/data/metar"
  status = 200
  force = true

  [redirects.headers]
    "User-Agent" = "flightplan/0.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  [dev.https]
    certFile = "certs/localhost.pem"
    keyFile = "certs/localhost-key.pem"